# inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false
